<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>net.geoprism.geoai.explorer</groupId>
		<artifactId>geo-ai-explorer</artifactId>
		<version>0.0.1-SNAPSHOT</version>
	</parent>
	<artifactId>geo-ai-explorer-api</artifactId>
	<packaging>war</packaging>
	<name>Geo AI explorer API server</name>
	<description></description>
	<properties>
		<maven.compiler.source>17</maven.compiler.source>
		<maven.compiler.target>17</maven.compiler.target>
		<java.version>17</java.version>
		<aws.version>2.47.4</aws.version>
		<spring.version>3.5.13</spring.version>
		<geotools.version>32.2</geotools.version>
	</properties>
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>software.amazon.awssdk</groupId>
				<artifactId>bom</artifactId>
				<version>${aws.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>
	<dependencies>
		<dependency>
			<groupId>software.amazon.awssdk</groupId>
			<artifactId>netty-nio-client</artifactId>
			<exclusions>
				<exclusion>
					<groupId>org.slf4j</groupId>
					<artifactId>slf4j-api</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

		<!--  Spring!  -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
			<version>${spring.version}</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-security</artifactId>
			<version>${spring.version}</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
			<version>${spring.version}</version>
		</dependency>
		<!-- 
    -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-tomcat</artifactId>
			<version>${spring.version}</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<version>${spring.version}</version>
			<scope>test</scope>
		</dependency>
		<!-- AWS -->
		<dependency>
		    <groupId>software.amazon.awssdk</groupId>
		    <artifactId>bedrockagentcore</artifactId>
		</dependency>
		<dependency>
			<groupId>software.amazon.awssdk</groupId>
			<artifactId>bedrock</artifactId>
		</dependency>
		<dependency>
			<groupId>software.amazon.awssdk</groupId>
			<artifactId>bedrockruntime</artifactId>
		</dependency>
		<dependency>
			<groupId>software.amazon.awssdk</groupId>
			<artifactId>http-auth-aws</artifactId>
		</dependency>
		<dependency>
			<groupId>com.amazonaws</groupId>
			<artifactId>amazon-neptune-sparql-java-sigv4</artifactId>
			<version>4.0.0</version>
			<exclusions>
		        <exclusion>
		            <groupId>org.slf4j</groupId>
		            <artifactId>slf4j-simple</artifactId>
		        </exclusion>
		    </exclusions>
		</dependency>
		<dependency>
			<groupId>software.amazon.awssdk</groupId>
			<artifactId>apache-client</artifactId>
		</dependency>
		<!-- Jena Client-->
		<dependency>
			<groupId>org.apache.jena</groupId>
			<artifactId>jena-rdfconnection</artifactId>
			<version>5.3.0</version>
		</dependency>
		<dependency>
			<groupId>org.apache.jena</groupId>
			<artifactId>jena-geosparql</artifactId>
			<version>5.3.0</version>
		</dependency>
		<!-- Open Search -->
		<dependency>
			<groupId>org.opensearch.client</groupId>
			<artifactId>opensearch-rest-client</artifactId>
			<version>3.6.0</version>
		</dependency>
		<dependency>
			<groupId>org.opensearch.client</groupId>
			<artifactId>opensearch-java</artifactId>
			<version>2.6.0</version>
		</dependency>

		<!-- https://mvnrepository.com/artifact/org.geotools/gt-geojson -->
		<dependency>
			<groupId>org.geotools</groupId>
			<artifactId>gt-geojson</artifactId>
			<version>${geotools.version}</version>
		</dependency>

		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<version>1.18.36</version>
			<scope>provided</scope>
		</dependency>
		
		<!-- Failsafe allows for easy retry behaviour -->
		<dependency>
		    <groupId>dev.failsafe</groupId>
		    <artifactId>failsafe</artifactId>
		    <version>3.3.2</version>
		</dependency>


		<!-- Testing -->
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.12</version>
			<scope>test</scope>
		</dependency>
		<!-- https://mvnrepository.com/artifact/org.geotools/gt-shapefile -->
		<dependency>
			<groupId>org.geotools</groupId>
			<artifactId>gt-shapefile</artifactId>
			<version>${geotools.version}</version>
			<scope>test</scope>

		</dependency>
		<dependency>
			<groupId>org.geotools</groupId>
			<artifactId>gt-epsg-hsql</artifactId>
			<version>${geotools.version}</version>
			<scope>test</scope>

		</dependency>
	</dependencies>

	<profiles>
		<profile>
			<id>category</id>
			<build>
				<plugins>
					<plugin>
						<artifactId>maven-failsafe-plugin</artifactId>
						<version>3.1.2</version>
						<configuration>
							<includes>
								<include>**/*IntegrationTest.java</include>
							</includes>
						</configuration>
						<executions>
							<execution>
								<goals>
									<goal>integration-test</goal>
									<goal>verify</goal>
								</goals>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>
		<profile>
			<id>cargo-run</id>
			<activation>
				<property>
					<name>cargo-run</name>
				</property>
			</activation>
			<build>
				<plugins>
					<plugin>
						<groupId>org.codehaus.cargo</groupId>
						<artifactId>cargo-maven2-plugin</artifactId>
						<version>1.9.0</version>
						<configuration>
							<container>
								<containerId>tomcat9x</containerId>
								<artifactInstaller>
									<groupId>org.apache.tomcat</groupId>
									<artifactId>tomcat</artifactId>
									<version>11.0.5</version>
								</artifactInstaller>
								<timeout>4800000</timeout>
							</container>
							<configuration>
								<properties>
									<cargo.servlet.port>8080</cargo.servlet.port>
									<cargo.protocol>http</cargo.protocol>
									<cargo.tomcat.httpSecure>false</cargo.tomcat.httpSecure>
									<cargo.tomcat.uriencoding>UTF-8</cargo.tomcat.uriencoding>
									<cargo.jvmargs>
										-Xmx5120M
										-Xdebug
										-Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=8000
										-Dtomcat.home=/${project.basedir}/target/cargo/configurations/tomcat8x
									</cargo.jvmargs>
								</properties>
							</configuration>
							<deployables>
								<deployable>
									<groupId>net.geoprism.geoai.explorer</groupId>
									<artifactId>geo-ai-explorer-api</artifactId>
									<type>war</type>
									<properties>
										<context>/</context>
									</properties>
								</deployable>
							</deployables>
						</configuration>
						<executions>
							<execution>
								<id>cargo-run</id>
								<phase>verify</phase>
								<goals>
									<goal>run</goal>
								</goals>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>

	<build>
		<sourceDirectory>src/main/java</sourceDirectory>
		<scriptSourceDirectory>scripts</scriptSourceDirectory>
		<testSourceDirectory>src/test/java</testSourceDirectory>
		<resources>
			<resource>
				<directory>src/main/resources</directory>
			</resource>
		</resources>
		<testResources>
			<testResource>
				<directory>src/test/resources</directory>
			</testResource>
		</testResources>
		<directory>target</directory>
		<finalName>geo-ai-explorer-api</finalName>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-war-plugin</artifactId>
				<version>3.4.0</version>
			</plugin>
			<plugin>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>3.5.2</version>
				<configuration>
					<excludes>
						<exclude>**IntegrationTest.java</exclude>
					</excludes>
				</configuration>
			</plugin>
			<!--  Copy over the compiled react code    -->
			<plugin>
				<artifactId>maven-resources-plugin</artifactId>
				<version>3.3.0</version>
				<executions>
					<execution>
						<id>copy-resources</id>
						<phase>process-resources</phase>
						<goals>
							<goal>copy-resources</goal>
						</goals>
						<configuration>
							<outputDirectory>
								${project.build.directory}/classes/static/</outputDirectory>
							<resources>
								<resource>
									<directory>
										${project.basedir}/../geo-ai-explorer-ui/dist/geo-ai-explorer/browser/</directory>
									<filtering>false</filtering>
								</resource>
							</resources>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</project>